name: Release custom

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag of the release"
        required: true
        type: string

jobs:
  approval: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      id: checkout_code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN}}

    - name: set_message
      id: set_message
      run: |
        git tag -l
        git tag -l "$TAG"
        TAG=${{ github.event.inputs.tag }}
        if ! git tag -l "$TAG" | grep -q "^$TAG$"; then
          echo "Error: $TAG is not a valid tag."
          exit 1
        fi
        SHA=$(git rev-list -n 1 "$TAG")
        echo "TITLE=Request to do custom release" >> $GITHUB_OUTPUT
        echo "BODY=Please approve or deny the release of version with tag $TAG. Commit SHA is: $SHA." >> $GITHUB_OUTPUT


    - name: get approval
      uses: trstringer/manual-approval@v1
      with: 
        secret: ${{ secrets.ACCESS_TOKEN}}
        approvers: approvers
        minimum-approvals: 1
        issue-title: ${{ steps.set_message.outputs.TITLE}}
        issue-body: ${{ steps.set_message.outputs.BODY}}
        exclude-workflow-initiator-as-approver: true

  print-details:
    runs-on: ubuntu-latest
    needs: approval

    steps:
    - name: Checkout code
      id: checkout_code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN}}

    - name: Greet
      id: greet
      run: |
        echo "Custom release  has been created and is now published! Commit SHA is: ${GITHUB_SHA}"
    
