name: Release version

on:
  release:
    types: [created]

jobs:
  approval: 
    runs-on: ubuntu-latest
    
    steps:
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.ACCESS_TOKEN}}
        approvers: approvers
        minimum-approvals: 1
        issue-title: "Request to release ${GITHUB_REF}"
        issue-body: "Please approve or deny the release of version ${GITHUB_REF}. Commit SHA is: ${GITHUB_SHA}."
        exclude-workflow-initiator-as-approver: false

  print-details:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout_code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN}}

    - name: Greet
      id: greet
      run: |
        echo "Release ${GITHUB_REF} has been created and is now published! Commit SHA is: ${GITHUB_SHA}"
    
