name: Release version

on:
  release:
    types: [created]

jobs:
  print-details:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout_code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN}}

    - name: Greet
      id: greet
      run: |
        echo "Release ${GITHUB_REF} has been created and is now published! Commit SHA is: ${GITHUB_SHA}"
    
