name: Release version

on:
  release:
    types: [created]

jobs:
  approval: 
    runs-on: ubuntu-latest
    
    steps:
    - name: set_message
      id: set_message
      run: |
        echo "TITLE=Request to release ${GITHUB_REF}" >> $GITHUB_OUTPUT
        echo "BODY=Please approve or deny the release of version ${GITHUB_REF}. Commit SHA is: ${GITHUB_SHA}." >> $GITHUB_OUTPUT


    - name: get approval
      uses: trstringer/manual-approval@v1
      with: 
        secret: ${{ secrets.ACCESS_TOKEN}}
        approvers: approvers
        minimum-approvals: 1
        issue-title: ${{ steps.set_message.outputs.TITLE}}
        issue-body: ${{ steps.set_message.outputs.BODY}}
        exclude-workflow-initiator-as-approver: true

  print-details:
    runs-on: ubuntu-latest
    needs: approval

    steps:
    - name: Checkout code
      id: checkout_code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN}}

    - name: Greet
      id: greet
      run: |
        echo "Release ${GITHUB_REF} has been created and is now published! Commit SHA is: ${GITHUB_SHA}"
    
