name: say hello world on demand.

on:
  workflow_dispatch:
    inputs:
      name: 
        description: "What is your name?"
        required: true
        default: "you"
        type: choice
        options:
          - alex
          - sarah
          - amy

      weather:
        description: "what is the weather?"
        required: true
        default: "rainy"
  
jobs:
  approval: 
    runs-on: ubuntu-latest
    
    steps:
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.ACCESS_TOKEN}}
        approvers: approvers
        minimum-approvals: 1
        issue-title: "Running hello world"
        issue-body: "Please approve or deny the running of hello world."
        exclude-workflow-initiator-as-approver: false


  greet:
    runs-on: ubuntu-latest
    needs: approval

    steps:
    - name: Checkout code
      id: checkout_code
      uses: actions/checkout@v4
      with:
        secret: ${{ secrets.ACCESS_TOKEN}}

    - name: Greet
      id: greet
      run: |
        echo "Hello  ${{ github.event.inputs.name }}, it is ${{ github.event.inputs.weather }} today."
